apiVersion: v1
kind: PersistentVolume
metadata:
  name: wt-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/wandering-trader"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wt-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
